### ISSUE TITLE
Reviewed Project

### ISSUE THREAD

**Issue by 15jennlee15** [alexisadamsclark/finalproject#3]
Hi, @alexisadamsclark @ajfridman and @xiy1992 

I reviewed your data prep script. Great Job! In order to provide you feedback, I forked your project and I made comments and edits in your R Markdown file in the forked version.  Please review this to see my comments https://github.com/15jennlee15/finalproject.git

Great work and look forward to seeing your presentation.
From Jenn Lewis
@datalorax Tagging you so you can see my peer review

**Comment by datalorax** [comment]
Hi Jenn,

So this is a little late (on my part) but the file you uploaded that had the comments was the HTML, which makes it a little more difficult to incorporate. If it's still relevant, it might be good to commit the Rmd to your fork too. I was able to see them but I had to clone your fork and then open the HTML file that way, rather than just looking at the commit diff. And actually, I'm not really sure if I'm looking at your comments or not...

Anyway, one bit of feedback for the group that I see is that you should definitely not have more than one R project in the repo. In this case it's a bit lucky because they're all in the same directory, but it can definitely lead to issues so I'd recommend removing them.

**Comment by alexisadamsclark** [comment]
Thank you!
